# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(upload_to='gallery/')),
                ('images_name', models.CharField(max_length=30)),
                ('images_description', models.CharField(max_length=60)),
                ('images_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Category')),
            ],
            options={
                'ordering': ['images_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='images_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Location'),
        ),
    ]
